package Vista.Operadores.VentanaOperadores;

import ValidacionDatosEntrada.ValidacionDatosEntrada;
import javax.swing.JFrame;
import java.awt.event.ActionListener;
import javax.swing.DefaultListSelectionModel;
import javax.swing.ListSelectionModel;

public class VentanaOperadores extends JFrame {

    /**
     * Crea una nueva ventana y la despliega en pantalla.
     */
    public VentanaOperadores() {
        initComponents();
        campoNroOperador.addKeyListener(new ValidacionDatosEntrada());     // Listener de validación de entrada para el campo 'Número de operador'
        tablaOperadores.setSelectionModel(new ForcedListSelectionModel());  // Limita la capacidad de selección de filas a una sóla por clic
    }

    /**
     * Registra el objeto ActionListener pasado como argumento como Listener del
     * botón 'Buscar'.
     *
     * @param ae Instancia ActionListener que se registra como Listener
     */
    public void agregarListenerBotonBuscar(ActionListener ae) {
        botonBuscar.addActionListener(ae);
    }

    /**
     * Registra el objeto ActionListener pasado como argumento como Listener del
     * botón 'Agregar operador'.
     *
     * @param ae Instancia ActionListener que se registra como Listener
     */
    public void agregarListenerBotonAgregarOperador(ActionListener ae) {
        botonAgregarOperador.addActionListener(ae);
    }

    /**
     * Registra el objeto ActionListener pasado como argumento como Listener del
     * botón 'Editar operador'.
     *
     * @param ae Instancia ActionListener que se registra como Listener
     */
    public void agregarListenerBotonEditarOperador(ActionListener ae) {
        botonEditarOperador.addActionListener(ae);
    }

    /**
     * Registra el objeto ActionListener pasado como argumento como Listener del
     * botón 'Eliminar operador'.
     *
     * @param ae Instancia ActionListener que se registra como Listener
     */
    public void agregarListenerBotonEliminarOperador(ActionListener ae) {
        botonEliminarOperador.addActionListener(ae);
    }

    /**
     * Devuelve el valor del atributo 'ID' (columna en la posición 0) de la
     * tabla.
     *
     * @return
     */
    public String getIDFila() {
        int filaSeleccionada = tablaOperadores.getSelectedRow();
        Object IDObtenido = tablaOperadores.getValueAt(filaSeleccionada, 0);    // La columna correspondiente a 'ID' es la 0.
        return IDObtenido.toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelScrolling = new javax.swing.JScrollPane();
        tablaOperadores = new javax.swing.JTable();
        panelBusqueda = new javax.swing.JPanel();
        botonBuscar = new javax.swing.JButton();
        campoNombreOperador = new javax.swing.JTextField();
        campoNroOperador = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        botonAgregarOperador = new javax.swing.JButton();
        botonEditarOperador = new javax.swing.JButton();
        botonEliminarOperador = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Operadores");
        setResizable(false);

        panelScrolling.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelScrolling.setToolTipText("");

        tablaOperadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaOperadores.setToolTipText("");
        panelScrolling.setViewportView(tablaOperadores);

        panelBusqueda.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Búsqueda", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        panelBusqueda.setToolTipText("Ingrese los criterios de búsqueda para encontrar socios");

        botonBuscar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ControladoresVistas/ControladorVentanaSocios/Iconos/Buscar_socio.png"))); // NOI18N
        botonBuscar.setText("Buscar operador");
        botonBuscar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        campoNombreOperador.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoNombreOperador.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Nombre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        campoNroOperador.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoNroOperador.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Número", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        javax.swing.GroupLayout panelBusquedaLayout = new javax.swing.GroupLayout(panelBusqueda);
        panelBusqueda.setLayout(panelBusquedaLayout);
        panelBusquedaLayout.setHorizontalGroup(
            panelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBusquedaLayout.createSequentialGroup()
                .addComponent(campoNombreOperador, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoNroOperador, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelBusquedaLayout.setVerticalGroup(
            panelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNombreOperador, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNroOperador))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBusquedaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonBuscar)
                .addContainerGap())
        );

        panelBusquedaLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {campoNombreOperador, campoNroOperador});

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("OPERADORES");

        botonAgregarOperador.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonAgregarOperador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ControladoresVistas/ControladorVentanaSocios/Iconos/Agregar_socio.png"))); // NOI18N
        botonAgregarOperador.setText("Agregar operador");
        botonAgregarOperador.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        botonEditarOperador.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonEditarOperador.setText("Editar operador");
        botonEditarOperador.setToolTipText("Presione para editar los datos del socio seleccionado.");
        botonEditarOperador.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        botonEliminarOperador.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonEliminarOperador.setText("Eliminar operador");
        botonEliminarOperador.setToolTipText("Presione para editar los datos del socio seleccionado.");
        botonEliminarOperador.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelScrolling, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(botonAgregarOperador, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(botonEditarOperador, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(botonEliminarOperador, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {botonAgregarOperador, botonEditarOperador, botonEliminarOperador});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelScrolling, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonAgregarOperador, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botonEditarOperador)
                        .addComponent(botonEliminarOperador)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {botonAgregarOperador, botonEditarOperador, botonEliminarOperador});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarOperador;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonEditarOperador;
    private javax.swing.JButton botonEliminarOperador;
    private javax.swing.JTextField campoNombreOperador;
    private javax.swing.JTextField campoNroOperador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelBusqueda;
    private javax.swing.JScrollPane panelScrolling;
    private javax.swing.JTable tablaOperadores;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JTable getTablaOperadores() {
        return tablaOperadores;
    }

    public javax.swing.JTextField getCampoNombreOperador() {
        return campoNombreOperador;
    }

    public javax.swing.JTextField getCampoNroOperador() {
        return campoNroOperador;
    }

    /**
     * Clase manejadora de los eventos de selección de la tabla de operadores.
     */
    public class ForcedListSelectionModel extends DefaultListSelectionModel {

        public ForcedListSelectionModel() {
            setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        }

        @Override
        public void clearSelection() {
        }

        @Override
        public void removeSelectionInterval(int index0, int index1) {
        }
    }
}
