package Vistas.VentanaSocios;

import ValidacionDatosEntrada.ValidacionDatosEntrada;
import javax.swing.JFrame;
import java.awt.event.ActionListener;
import javax.swing.DefaultListSelectionModel;
import javax.swing.ListSelectionModel;

public class VentanaSocios extends JFrame {

    /**
     * Crea una nueva ventana y la despliega en pantalla.
     */
    public VentanaSocios() {
        initComponents();
        this.setVisible(true);
        campoNroSocio.addKeyListener(new ValidacionDatosEntrada());     // Listener de validación de entrada para el campo 'Número de socio'
        tablaSocios.setSelectionModel(new ForcedListSelectionModel());  // Limita la capacidad de selección de filas a uno
    }

    /**
     * Registra el objeto ActionListener pasado como argumento como Listener del
     * botón 'Buscar'.
     *
     * @param ae Instancia ActionListener que se registra como Listener
     */
    public void agregarListenerBotonBuscar(ActionListener ae) {
        botonBuscar.addActionListener(ae);
    }

    /**
     * Registra el objeto ActionListener pasado como argumento como Listener del
     * botón 'Agregar socio'.
     *
     * @param ae Instancia ActionListener que se registra como Listener
     */
    public void agregarListenerBotonAgregarSocio(ActionListener ae) {
        botonAgregarSocio.addActionListener(ae);
    }

    /**
     * Registra el objeto ActionListener pasado como argumento como Listener del
     * botón 'Editar socio'.
     *
     * @param ae Instancia ActionListener que se registra como Listener
     */
    public void agregarListenerBotonEditarSocio(ActionListener ae) {
        botonEditarSocio.addActionListener(ae);
    }

    /**
     * Registra el objeto ActionListener pasado como argumento como Listener del
     * botón 'Eliminar socio'.
     *
     * @param ae Instancia ActionListener que se registra como Listener
     */
    public void agregarListenerBotonEliminarSocio(ActionListener ae) {
        botonEliminarSocio.addActionListener(ae);
    }

    /**
     * Devuelve el valor del atributo 'ID' (columna en la posición 0) de la
     * tabla.
     *
     * @return
     */
    public String getIDFila() {
        int filaSeleccionada = tablaSocios.getSelectedRow();
        Object IDObtenido = tablaSocios.getValueAt(filaSeleccionada, 0);    // La columna correspondiente a 'ID' es la 0.
        return IDObtenido.toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelScrolling = new javax.swing.JScrollPane();
        tablaSocios = new javax.swing.JTable();
        panelBusqueda = new javax.swing.JPanel();
        botonBuscar = new javax.swing.JButton();
        campoNombreSocio = new javax.swing.JTextField();
        campoNroSocio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        botonAgregarSocio = new javax.swing.JButton();
        botonEditarSocio = new javax.swing.JButton();
        botonEliminarSocio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Socios");
        setResizable(false);

        panelScrolling.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelScrolling.setToolTipText("");

        tablaSocios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaSocios.setToolTipText("");
        panelScrolling.setViewportView(tablaSocios);

        panelBusqueda.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Buscar socios", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        panelBusqueda.setToolTipText("Ingrese los criterios de búsqueda para encontrar socios");

        botonBuscar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ControladoresVistas/ControladorVentanaSocios/Iconos/Buscar_socio.png"))); // NOI18N
        botonBuscar.setText("Buscar socio");
        botonBuscar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        campoNombreSocio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoNombreSocio.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Nombre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        campoNroSocio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoNroSocio.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Número", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        javax.swing.GroupLayout panelBusquedaLayout = new javax.swing.GroupLayout(panelBusqueda);
        panelBusqueda.setLayout(panelBusquedaLayout);
        panelBusquedaLayout.setHorizontalGroup(
            panelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBusquedaLayout.createSequentialGroup()
                .addComponent(campoNombreSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoNroSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelBusquedaLayout.setVerticalGroup(
            panelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNombreSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNroSocio))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBusquedaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonBuscar)
                .addContainerGap())
        );

        panelBusquedaLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {campoNombreSocio, campoNroSocio});

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("SOCIOS");

        botonAgregarSocio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonAgregarSocio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ControladoresVistas/ControladorVentanaSocios/Iconos/Agregar_socio.png"))); // NOI18N
        botonAgregarSocio.setText("Agregar nuevo socio");
        botonAgregarSocio.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        botonEditarSocio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonEditarSocio.setText("Editar socio");
        botonEditarSocio.setToolTipText("Presione para editar los datos del socio seleccionado.");
        botonEditarSocio.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        botonEliminarSocio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonEliminarSocio.setText("Eliminar socio");
        botonEliminarSocio.setToolTipText("Presione para editar los datos del socio seleccionado.");
        botonEliminarSocio.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelScrolling, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(botonAgregarSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(botonEditarSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(botonEliminarSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {botonAgregarSocio, botonEditarSocio, botonEliminarSocio});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelScrolling, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonAgregarSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botonEditarSocio)
                        .addComponent(botonEliminarSocio)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {botonAgregarSocio, botonEditarSocio, botonEliminarSocio});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarSocio;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonEditarSocio;
    private javax.swing.JButton botonEliminarSocio;
    private javax.swing.JTextField campoNombreSocio;
    private javax.swing.JTextField campoNroSocio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelBusqueda;
    private javax.swing.JScrollPane panelScrolling;
    private javax.swing.JTable tablaSocios;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JTable getTablaSocios() {
        return tablaSocios;
    }

    public javax.swing.JTextField getCampoNombreSocio() {
        return campoNombreSocio;
    }

    public javax.swing.JTextField getCampoNroSocio() {
        return campoNroSocio;
    }

    /**
     * Clase manejadora de los eventos de selección de la tabla. de socios.
     */
    public class ForcedListSelectionModel extends DefaultListSelectionModel {

        public ForcedListSelectionModel() {
            setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        }

        @Override
        public void clearSelection() {
        }

        @Override
        public void removeSelectionInterval(int index0, int index1) {
        }
    }
}
