package Vista.Cobradores.VentanaCobradores;

import ValidacionDatosEntrada.ValidacionDatosEntrada;
import javax.swing.JFrame;
import java.awt.event.ActionListener;
import javax.swing.DefaultListSelectionModel;
import javax.swing.ListSelectionModel;

public class VentanaCobradores extends JFrame {

    /**
     * Crea una nueva ventana y la despliega en pantalla.
     */
    public VentanaCobradores() {
        initComponents();
        campoNroCobrador.addKeyListener(new ValidacionDatosEntrada());     // Listener de validación de entrada para el campo 'Número de cobrador'
        tablaCobradores.setSelectionModel(new ForcedListSelectionModel());  // Limita la capacidad de selección de filas a una sóla por clic
    }

    /**
     * Registra el objeto ActionListener pasado como argumento como Listener del
     * botón 'Buscar'.
     *
     * @param ae Instancia ActionListener que se registra como Listener
     */
    public void agregarListenerBotonBuscar(ActionListener ae) {
        botonBuscar.addActionListener(ae);
    }

    /**
     * Registra el objeto ActionListener pasado como argumento como Listener del
     * botón 'Agregar cobrador'.
     *
     * @param ae Instancia ActionListener que se registra como Listener
     */
    public void agregarListenerBotonAgregarCobrador(ActionListener ae) {
        botonAgregarCobrador.addActionListener(ae);
    }

    /**
     * Registra el objeto ActionListener pasado como argumento como Listener del
     * botón 'Editar cobrador'.
     *
     * @param ae Instancia ActionListener que se registra como Listener
     */
    public void agregarListenerBotonEditarCobrador(ActionListener ae) {
        botonEditarCobrador.addActionListener(ae);
    }

    /**
     * Registra el objeto ActionListener pasado como argumento como Listener del
     * botón 'Eliminar cobrador'.
     *
     * @param ae Instancia ActionListener que se registra como Listener
     */
    public void agregarListenerBotonEliminarCobrador(ActionListener ae) {
        botonEliminarCobrador.addActionListener(ae);
    }

    /**
     * Devuelve el valor del atributo 'ID' (columna en la posición 0) de la
     * tabla.
     *
     * @return
     */
    public String getIDFila() {
        int filaSeleccionada = tablaCobradores.getSelectedRow();
        Object IDObtenido = tablaCobradores.getValueAt(filaSeleccionada, 0);    // La columna correspondiente a 'ID' es la 0.
        return IDObtenido.toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelScrolling = new javax.swing.JScrollPane();
        tablaCobradores = new javax.swing.JTable();
        panelBusqueda = new javax.swing.JPanel();
        botonBuscar = new javax.swing.JButton();
        campoNombreCobrador = new javax.swing.JTextField();
        campoNroCobrador = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        botonAgregarCobrador = new javax.swing.JButton();
        botonEditarCobrador = new javax.swing.JButton();
        botonEliminarCobrador = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cobradores");
        setResizable(false);

        panelScrolling.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelScrolling.setToolTipText("");

        tablaCobradores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaCobradores.setToolTipText("");
        panelScrolling.setViewportView(tablaCobradores);

        panelBusqueda.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        panelBusqueda.setToolTipText("Ingrese los criterios de búsqueda para encontrar socios");

        botonBuscar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ControladoresVistas/ControladorVentanaSocios/Iconos/Buscar_socio.png"))); // NOI18N
        botonBuscar.setText("Buscar cobrador");
        botonBuscar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        campoNombreCobrador.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoNombreCobrador.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Nombre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        campoNroCobrador.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoNroCobrador.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Número", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        javax.swing.GroupLayout panelBusquedaLayout = new javax.swing.GroupLayout(panelBusqueda);
        panelBusqueda.setLayout(panelBusquedaLayout);
        panelBusquedaLayout.setHorizontalGroup(
            panelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBusquedaLayout.createSequentialGroup()
                .addComponent(campoNombreCobrador, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoNroCobrador, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelBusquedaLayout.setVerticalGroup(
            panelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNombreCobrador, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNroCobrador))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBusquedaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonBuscar)
                .addContainerGap())
        );

        panelBusquedaLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {campoNombreCobrador, campoNroCobrador});

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("COBRADORES");

        botonAgregarCobrador.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonAgregarCobrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ControladoresVistas/ControladorVentanaSocios/Iconos/Agregar_socio.png"))); // NOI18N
        botonAgregarCobrador.setText("Agregar cobrador");
        botonAgregarCobrador.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        botonEditarCobrador.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonEditarCobrador.setText("Editar cobrador");
        botonEditarCobrador.setToolTipText("Presione para editar los datos del socio seleccionado.");
        botonEditarCobrador.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        botonEliminarCobrador.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonEliminarCobrador.setText("Eliminar cobrador");
        botonEliminarCobrador.setToolTipText("Presione para editar los datos del socio seleccionado.");
        botonEliminarCobrador.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelScrolling, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(botonAgregarCobrador, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(botonEditarCobrador, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(botonEliminarCobrador, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {botonAgregarCobrador, botonEditarCobrador, botonEliminarCobrador});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelScrolling, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonAgregarCobrador, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botonEditarCobrador)
                        .addComponent(botonEliminarCobrador)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {botonAgregarCobrador, botonEditarCobrador, botonEliminarCobrador});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarCobrador;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonEditarCobrador;
    private javax.swing.JButton botonEliminarCobrador;
    private javax.swing.JTextField campoNombreCobrador;
    private javax.swing.JTextField campoNroCobrador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelBusqueda;
    private javax.swing.JScrollPane panelScrolling;
    private javax.swing.JTable tablaCobradores;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JTable getTablaCobradores() {
        return tablaCobradores;
    }

    public javax.swing.JTextField getCampoNombreCobrador() {
        return campoNombreCobrador;
    }

    public javax.swing.JTextField getCampoNroCobrador() {
        return campoNroCobrador;
    }

    /**
     * Clase manejadora de los eventos de selección de la tabla de cobradores.
     */
    public class ForcedListSelectionModel extends DefaultListSelectionModel {

        public ForcedListSelectionModel() {
            setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        }

        @Override
        public void clearSelection() {
        }

        @Override
        public void removeSelectionInterval(int index0, int index1) {
        }
    }
}
